<a href="https://colab.research.google.com/github/mo7emmed/mo7emmed/blob/Courses/Intro_to_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
s = np.array ([4])
s

array([4])

In [ ]:
type (s)

numpy.ndarray

In [ ]:
s.shape

(1,)

In [ ]:
t = np.array ([3, 2, 1])
t

array([3, 2, 1])

In [ ]:
t.shape

(3,)

In [ ]:
t.reshape(3,1)

array([[3],
       [2],
       [1]])

In [ ]:
t.shape

(3,)

In [ ]:
t2 = np.array ([2, 4, 7])

In [ ]:
m1 = np.array ([[4,5,7], [3,2,9]])
m1

array([[4, 5, 7],
       [3, 2, 9]])

In [ ]:
m1.reshape(2,3)

array([[4, 5, 7],
       [3, 2, 9]])

In [ ]:
m2 = np.array([[5,3,4], [8,1,6]])
m2

array([[5, 3, 4],
       [8, 1, 6]])

In [ ]:
m = m1, m2
m

(array([[4, 5, 7],
        [3, 2, 9]]),
 array([[5, 3, 4],
        [8, 1, 6]]))

In [ ]:
s = m1 + m2
s

array([[ 9,  8, 11],
       [11,  3, 15]])

In [ ]:
np.dot(t,t2)

21

In [ ]:
np.shape(m1)

(2, 3)

In [ ]:
np.shape(m2)

(2, 3)

In [ ]:
m2.reshape(3,2)
m2

array([[5, 3, 4],
       [8, 1, 6]])

In [ ]:
m1.reshape(3, 2)
m1

array([[4, 5, 7],
       [3, 2, 9]])

In [ ]:
m3 = np.array([[2,3,1], [4, 7, 1], [8, 1, 1]])
m3

array([[2, 3, 1],
       [4, 7, 1],
       [8, 1, 1]])

In [ ]:
np.dot(m1, m3)

array([[84, 54, 16],
       [86, 32, 14]])

In [ ]:
a= np.array([[5,21,6], [11, 8, 62]])
b = np.array([[4, 5], [6, 7], [10, 3]])

In [ ]:
np.dot(a,b)

array([[206, 190],
       [712, 297]])

In [ ]:
np.dot(4,b)

array([[16, 20],
       [24, 28],
       [40, 12]])

In [ ]:
md = np.array ([[1,2,3], [4, 5, 6]])
md2 = np.array ([[4,3, 1, 2], [5, 6, 1, 1], [1, 1, 1, 2]])

In [ ]:
np.dot(md,md2)

array([[17, 18,  6, 10],
       [47, 48, 15, 25]])

In [ ]:
m1 = np.array([[1,3,2,5,1], [2,1,2,1,2], [3,1,3,2,1]])
m2 = np.array([[2,1], [4,2], [1,1], [3,1], [5,3]])

In [ ]:
np.dot(m1,m2)

array([[36, 17],
       [23, 13],
       [24, 13]])

In [ ]:
p = np.array([[1, 2, 3], [5, 6, 7]])
p

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
p2 = p.T

In [ ]:
p

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
p2

array([[1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
p.shape

(2, 3)

In [ ]:
p2.shape

(3, 2)

In [ ]:
p1 = p.reshape(3, 2)

In [ ]:
p1

array([[1, 2],
       [3, 5],
       [6, 7]])

In [ ]:
p1.shape

(3, 2)

In [ ]:
s = np.array([ [[1,2], [3,4]], [[5,6],[7,8]], [[9,10],[11,12]] ])
m= np.array([ [[-2,-2],[3,14]], [[15,-2],[7,8]], [[29,10],[21,32]] ])
s[0]+m[1]


array([[16,  0],
       [10, 12]])

In [ ]:
a = np.array([[1, 1, 4], [1, 0, 2], [4, 2, 5]])
a*a.T

array([[ 1,  1, 16],
       [ 1,  0,  4],
       [16,  4, 25]])

In [ ]:
n = np.array([[1,2,1], [1,2,1]])
n1 = np.array([[1,2,1], [0,2,1], [2,3,4]])
n2 = np.array([[2,0,1], [2,1,1], [0,0,1]])
nn= np.dot(n,n1)
np.dot(nn,n2)+5

array([[29, 14, 24],
       [29, 14, 24]])